### ISSUE TITLE
Error: There is already a collection named "parties"

### ISSUE THREAD

**Issue by mryraghi** [Urigo/meteor-angular2.0-socially#133]
During the first steps of the tutorial the file `collections/parties.ts` is created. When Meteor restarts everything's fine but when it restarts again I get: 

```
W20160802-19:43:46.824(2)? (STDERR) Error: There is already a collection named "parties"
W20160802-19:43:46.824(2)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:244:15)
W20160802-19:43:46.824(2)? (STDERR)     at meteorInstall.collections.parties.js (/Users/Romeo/Documents/Projects/socially/.meteor/local/build/programs/server/app/app.js:15:19)
W20160802-19:43:46.825(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160802-19:43:46.825(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160802-19:43:46.825(2)? (STDERR)     at /Users/Romeo/Documents/Projects/socially/.meteor/local/build/programs/server/app/app.js:114:1
W20160802-19:43:46.825(2)? (STDERR)     at /Users/Romeo/Documents/Projects/socially/.meteor/local/build/programs/server/boot.js:297:10
W20160802-19:43:46.825(2)? (STDERR)     at Array.forEach (native)
W20160802-19:43:46.825(2)? (STDERR)     at Function._.each._.forEach (/Users/Romeo/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160802-19:43:46.825(2)? (STDERR)     at /Users/Romeo/Documents/Projects/socially/.meteor/local/build/programs/server/boot.js:133:5
```

If I change it to `parties.js` as mentioned in Meteor's official tutorial everything seems working. Of course, I still get tons of any kind of typescript warnings but it seems I have to get used to.

Can somebody help me, please?

**Comment by artmadeit** [comment]
See this issue https://github.com/Urigo/angular2-meteor/issues/318 it can helps :)

**Comment by mryraghi** [comment]
@ArthurMauricioDelgadillo thank you, I wonder why I didn't find it among the closed ones 😄
