### ISSUE TITLE
build failed   [downloaded code 2017-01-01,]

### ISSUE THREAD

**Issue by K69G4JRA725W** [Urigo/meteor-angular2.0-socially#209]
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:205:14
    at C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:232:16
    at C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by elpagano** [comment]
Same error in Linux
