### ISSUE TITLE
Cannot find module: 'meteor-accounts-ui', 'meteor-accounts', 'ng2-pagination'

### ISSUE THREAD

**Issue by devilleweppenaar** [Urigo/meteor-angular2.0-socially#26]
I ran into a few errors while following the [Socially tutorial](http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping). As a sanity check I tried with the latest code from this repo (both master branch and step 15 release archive), but got the same errors. I tried to debug it myself, but I got stuck unfortunately. :disappointed: 

The errors I got are as follows:

``` bash
=> Started proxy.                             
=> Started MongoDB.                           
client/parties-list/parties-list.ts (14, 26): Cannot find module 'meteor-accounts-ui'.
client/parties-list/parties-list.ts (16, 26): Cannot find module 'meteor-accounts'.
client/parties-list/parties-list.ts (20, 70): Cannot find module 'ng2-pagination'.
client/parties-list/parties-list.ts (57, 32): Cannot find name 'Counts'.
client/parties-list/parties-list.ts (2, 1): File 'typings/meteor-accounts-ui.d.ts' not found.
client/parties-list/parties-list.ts (3, 1): File 'typings/ng2-pagination.d.ts' not found.
client/parties-list/parties-list.ts (4, 1): File 'typings/meteor-accounts.d.ts' not found.
server/parties.ts (34, 5): Cannot find name 'Counts'.
=> Errors prevented startup:                  

   While processing files with barbatus:angular2 (for target web.browser):
   <anonymous>: Unknown absolute import path typings/meteor-accounts-ui.d.ts
   at Error (<anonymous>)
   at multi-file-caching-compiler.js:134:21
   at Array.forEach (native)
   at multi-file-caching-compiler.js:132:33
   at multi-file-caching-compiler.js:144:68
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:324:29
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:44:16
   at multi-file-caching-compiler.js:148:9
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
   at /Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:328:15
   at Object.async.forEachLimit.async.eachLimit (/Users/deville.weppenaar/.meteor/packages/barbatus_angular2/.0.7.3.18z368n++os+web.browser+web.cordova/plugin.Compilers.os/npm/caching-compiler/node_modules/async/lib/async.js:221:35)
   at TsCachingCompiler.processFilesForTarget (multi-file-caching-compiler.js:95:11)
   at TsCachingCompiler.processFilesForTarget (compilers/ts_caching_compiler.js:38:32)
   at TsCompiler.processFilesForTarget (compilers/ts_compiler.js:12:29)


=> Your application has errors. Waiting for file change.
```

This is the structure of my 'typings' folder:

```
typings
|-- angular2
    |-- platform
        |-- browser.d.ts
    |-- bootstrap.d.ts
    |-- common.d.ts
    |-- core.d.ts
    |-- router.d.ts
|-- es6-promise
    |-- es6-promise.d.ts
|-- meteor
    |-- meteor.d.ts
|-- angular2.d.ts
|-- angular2-meteor.d.ts
|-- party.d.ts
```

These are the steps I followed:
1. Ran `meteor create socially`
2. Removed initial files
3. Placed files from this repo inside 'socially' folder
4. Added meteor angular 2: (`meteor add urigo:angular2-meteor`)
5. Removed 'blaze-html-templates' and 'ecmascript' (`meteor remove blaze-html-templates ecmascript`)
6. Removed 'autopublish' and 'insecure' (`meteor remove autopublish insecure`)
7. Ran `meteor`, which generated additional typings
8. Ran `meteor` again, and got the errors as listed above

**Comment by barbatus** [comment]
It looks like you are missing meteor-accounts-ui, meteor-accounts and ng2-pagination packages.
Each of these packages install own typings, which you don't have, as I see, in the typings folder.
You might need to re-read 9 and 12 tutorial steps carefully.

**Comment by devilleweppenaar** [comment]
Thanks for the response @barbatus! However, I initially tried adding the packages as `meteor add meteor-accounts-ui meteor-accounts ng2-pagination`, but got some 'no such package' errors:

``` bash
 => Errors while parsing arguments:           

While adding package meteor-accounts-ui:
error: no such package

While adding package meteor-accounts:
error: no such package

While adding package ng2-pagination:
error: no such package
```

But when I did a search I found that I was missing the `barbatus:` on some of them, and the name of the packages on atmosphere aren't exactly the same.

I got the packages installed by issuing `meteor add barbatus:ng2-pagination barbatus:ng2-meteor-accounts-ui barbatus:ng2-meteor-accounts`.

I think the tutorial should be updated at some point to list these additional dependencies.

**Comment by barbatus** [comment]
You didn't read carefully neither the tutorial nor my previous comment.
9 and 12 tutorial steps are all about these packages.

**Comment by devilleweppenaar** [comment]
Oops, I see now! My apologies and thanks for the reply. Glad it was just me being a noob. :smile:

**Comment by bedrytskyi** [comment]
I have a problem on step 8 too. after installing `meteor npm install --save angular2-meteor-accounts-ui` it shows me:

├── UNMET PEER DEPENDENCY @angular/router-deprecated@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY angular2-meteor@0.6.0
└── angular2-meteor-accounts-ui@0.5.0 

npm WARN angular2-meteor-accounts-ui@0.5.0 requires a peer of @angular/router-deprecated@^2.0.0-rc.1 but none was installed.
npm WARN angular2-meteor-auto-bootstrap@0.5.6 requires a peer of angular2-meteor@^0.5.6 but none was installed.

After that app won't even start - blank page. What do I need to do? Hoping for a quick answer, because I hope to move next.

**Comment by vaideesRv** [comment]
How to solve this issue?

Errors prevented startup:

   While processing files with barbatus:angular2 (for target web.browser):
   packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:104:14: fs.existsSync is not a function
   at TypeScriptCompiler.copyTypings (packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:104:14)
   at packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:64:16
   at Array.forEach (native)
   at TypeScriptCompiler.processTypings (packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:50:11)
   at TypeScriptCompiler.processFilesForTarget
   (packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:115:12)


   While processing files with barbatus:angular2 (for target os.windows.x86_32):
   packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:104:14: fs.existsSync is not a function
   at TypeScriptCompiler.copyTypings (packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:104:14)
   at packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:64:16
   at Array.forEach (native)
   at TypeScriptCompiler.processTypings (packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:50:11)
   at TypeScriptCompiler.processFilesForTarget
   (packages/barbatus:ng2-typescript-compiler/typescript-compiler.js:115:12)
